#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server
# Check if enough parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer the file to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

# Display success or failure message
if [ "$?" -eq 0 ]; then
        echo "File transfer successful!"
else
        echo "Error: File transfer failed."