#!/usr/bin/env bash
# installs nginx and configures it on a remote server and listens to port 80

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html
cat << EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 "Hello World!";
    }
}
EOL
service nginx restart