#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with
#+ a sleep interval and displays "I am invincible!!!" when receiving a SIGTERM signal.

while true; do
    sleep 2
    trap 'echo "I am invincible!!!"; exit' SIGTERM
done
