#!/usr/bin/env bash
# A Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
  fi
done
